DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  ID INT AUTO_INCREMENT,
  LOGIN VARCHAR(16),
  FIRST_NAME VARCHAR(32),
  LAST_NAME VARCHAR(32),
  MAIL VARCHAR(32),
  PRIMARY KEY(ID));

INSERT INTO USERS (LOGIN, FIRST_NAME, LAST_NAME, MAIL)
VALUES ('user', 'Test', 'User', 'mail1@mail.com');

INSERT INTO USERS (LOGIN, FIRST_NAME, LAST_NAME, MAIL)
VALUES ('test', 'Another', 'User', 'mail2@mail.com');