CREATE TABLE Users (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  SURNAME VARCHAR(256) NOT NULL,
  BIRTHDAY DATE,
  PRIMARY KEY (id)
);

CREATE TABLE Friendship (
  userId1 INT NOT NULL,
  userId2 INT NOT NULL,
  PRIMARY KEY (userId1, userId2)
);

CREATE TABLE Posts (
  id INT AUTO_INCREMENT,
  userId INT NOT NULL,
  text VARCHAR(2048)
);

CREATE TABLE Likes (
  postId INT NOT NULL,
  userId INT NOT NULL,
  time TIMESTAMP NOT NULL,
);