CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(32),
  LAST_NAME VARCHAR(32),
  MAIL VARCHAR(32),
  LOGIN VARCHAR(16),
  PRIMARY KEY(ID));

CREATE TABLE IF NOT EXISTS LOGO (
  ID INT AUTO_INCREMENT,
  LOGO BINARY,
  PRIMARY KEY(ID));

DELETE FROM USERS;
DELETE FROM LOGO;

INSERT INTO USERS (LOGIN, FIRST_NAME, LAST_NAME, MAIL)
VALUES ('user', 'Test', 'User', 'mail1@mail.com');

INSERT INTO USERS (LOGIN, FIRST_NAME, LAST_NAME, MAIL)
VALUES ('test', 'Another', 'User', 'mail2@mail.com');
